function voxel_volume = load_dump(dump_name)
%save_dump Loads a 3D float volume from a file with the format generated by the backprojection tool and accepted by the visualization tool
    if ~exist(dump_name, 'file')
        errorf('%s does not exist\n', dump_name);
    end
    if ~contains(dump_name, {'.hdf5', '.h5'})
        f_id = fopen(dump_name);

        grid_size = abs(fread(f_id, 1, '*int32', 'ieee-be'));

        voxel_volume = permute(reshape(fread(f_id, grid_size^3, 'single', 'ieee-be'), ...
            [grid_size, grid_size, grid_size]), [3,2,1]);

        fclose(f_id);
    else
        voxel_volume = [];
        valid_names = {'/voxelVolume', '/voxel_volume', '/volume'};
        for dsname = valid_names
            try
                voxel_volume = h5read(dump_name, char(dsname));
                break;
            catch
                continue;
            end
        end
    end
end
